name: driving_school_controller
description: easy way to note answers for driving license sessions

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: any
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  enum_to_string: ^1.0.9
  localize_and_translate: ^2.2.2
  flutter_audio_recorder: ^0.5.5
  audioplayers: ^0.15.1
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
